library setram.globals;

var StationsList = [
  "Ruisseau",
  "Les Fusillés",
  "Tripoli-Thaalibia",
  "Tripoli-Mosquée",
  "Tripoli-Hamadache",
  "Tripoli-maqqaria",
  "Caroubier",
  "La Glacière",
  "Pont El Harrach",
  "BelleVue",
  "Bekri Bougerra",
  "Cinq Maisons",
  "Foire d'Alger",
  "Les Pins",
  "Tamaris",
  "Cité Mokhtar Zerhouni",
  "Cité Rabia Tahar",
  "Université de BabEzzouar",
  "Cité 5 Juillet",
  "Bab Ezzouar-Le pont",
  "Cité Universitaire Cube1",
  "Cité 8 Mai 1945",
  "Cité Clair Matin",
  "Bordj El Kiffan Lycée",
  "Bordj El Kiffan Centre",
  "Bordj El Kiffan Polyclinique",
  "Mouhous",
  "Mimouni Mahmoud",
  "Ben Merabet",
  "Ben Redouane",
  "Ben Mered",
  "Sidi Dris",
  "Ben Zerga",
  "Ben Zerga",
  "Café Chergui",
  "Faculté Biomédicale",
  "Cité Diplomatique",
  "Dergana centre",
];
